language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  # always install unittest2 on py26 even if $DEPS is unset
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* && $DEPS == true ]]; then pip install --use-mirrors futures mock pycares pycurl twisted http://pypi.python.org/packages/source/M/Monotime/Monotime-1.0.tar.gz; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $DEPS == true ]]; then pip install --use-mirrors sphinx; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' && $DEPS == true ]]; then pip install --use-mirrors futures mock; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' && $DEPS == true ]]; then pip install --use-mirrors pycares mock; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' && $DEPS == true ]]; then pip install --use-mirrors pycares; fi
  - python setup.py install
  - pip install --use-mirrors coveralls
# command to run tests, e.g. python setup.py test
script:  
  - python runtest
